{% set name = "python-oxmsg" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_oxmsg-{{ version }}.tar.gz
  sha256: a6aff4deb1b5975d44d49dab1d9384089ffeec819e19c6940bc7ffbc84775fad

build:
  entry_points:
    - oxmsg = oxmsg.cli:oxmsg
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - pip
  run:
    - typing_extensions >=4.9.0
    - python >={{ python_min }}
    - click
    - olefile
    - typing-extensions >=4.9.0

test:
  imports:
    - oxmsg
  commands:
    - pip check
    - oxmsg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scanny/python-oxmsg
  summary: Extract attachments from Outlook .msg files.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
